# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_nbmodular',
                'doc_host': 'https://JaumeAmoresDS.github.io',
                'git_url': 'https://github.com/JaumeAmoresDS/test_nbmodular',
                'lib_path': 'test_nbmodular'},
  'syms': {'test_nbmodular.core': {'test_nbmodular.core.foo': ('core.html#foo', 'test_nbmodular/core.py')}}}
